var path = require('path'),
  os = require('os'),
  // if the operation system is Windows
  isWin = os.platform().toLowerCase().indexOf('win') !== -1;
// require('../ckeditor/ckeditor.js'.replace(/\//g, path.sep));
module.exports = function (config) {
  config.set({
    basePath: '../js/classes'.replace(/\//g, path.sep),
    autoWatch: true,
    frameworks: ['jasmine'],
    files: [
      'helpers.js',
      'unit.js',
      'properties.js',
      'attributes.js',
      'tableattributes.js',
      'linkattributes.js',
      'style.js',
      'content.js',
      'tag.js',
      'plaintext.js',
      'table.js',
      'cell.js',
      'row.js',
      'listItem.js',
      'list.js',
      'olist.js',
      'ulist.js',
      'link.js',
      'selection.js',
      'string.js',
      'CKHelper.js',
      'Factory.js',
      'Registry.js',
      '../../jasmine/spec/HelperSpec.js',
      '../../jasmine/spec/UnitSpec.js',
      '../../jasmine/spec/PropertiesSpec.js',
      '../../jasmine/spec/AttributesSpec.js',
      '../../jasmine/spec/LinkAttributesSpec.js',
      '../../jasmine/spec/TableAttributesSpec.js',
      '../../jasmine/spec/StyleSpec.js',
      '../../jasmine/spec/TagSpec.js',
      '../../jasmine/spec/PlainTextSpec.js',
      '../../jasmine/spec/TableSpec.js',
      '../../jasmine/spec/RowSpec.js',
      '../../jasmine/spec/CellSpec.js',
      '../../jasmine/spec/ListItemSpec.js',
      '../../jasmine/spec/ListSpec.js',
      '../../jasmine/spec/OListSpec.js',
      '../../jasmine/spec/UListSpec.js',
      '../../jasmine/spec/LinkSpec.js',
      '../../jasmine/spec/CKHelperSpec.js',
      '../../jasmine/spec/SelectionSpec.js',
      '../../jasmine/spec/ContentSpec.js',
      '../../jasmine/spec/StringSpec.js',
      '../../jasmine/spec/FactorySpec.js',
      '../../jasmine/spec/RegistrySpec.js',
      '../../ckeditor/ckeditor.js'
    ].map(function(str){return str.replace(/\//g, path.sep);}),
    browsers: isWin ? ['Firefox', 'Chrome', 'IE'] : ['/usr/lib/chromium-browser/chromium-browser', 'Firefox'],
    reporters: ['progress', 'coverage'],
    preprocessors: { '*.js': ['coverage'] },
    coverageReporter: {
      type : 'html',
      dir : '../../test/coverage'.replace(/\//g, path.sep),
    },
    singleRun: true
  });
};
